### ISSUE TITLE
Construct a distributional thesaurus with the current pipeline on Wikipedia corpus

### ISSUE THREAD

**Issue by alexanderpanchenko** [tudarmstadt-lt/noun-sense-induction-scala#1]
Motivation
------

To learn the current framework and details of its implementation you need to calculate a word similarity graph (a distributional thesaurus, a DT) with the current pipeline. This is needed to better understand how it works and how it can be optimised. 

Implementation
----------

1. Download Wikipedia corpus: http://cental.fltr.ucl.ac.be/team/~panchenko/data/corpora/wacky-surface.csv. 

2. For testing purposes make a subcorpus of 50Mb and 500Mb. First do all the experiments on these smaller chunks. Then proceed with the entire 5Gb dataset. All experiments are conducted locally on your machine. 

3. Execute steps until "Compute DT (noun-sense-induction-scala)" according to this instruction. https://github.com/tudarmstadt-lt/noun-sense-induction-scala. 

4. Upload the result files (DT, feature matrix, etc) to Dropbox or any other place and put link for download here.

**Comment by mmbspk** [comment]
https://www.dropbox.com/sh/gimydm53vh7fae1/AACq2xV3WTJY8xnw-muVq7vha?dl=0

**Comment by alexanderpanchenko** [comment]
Thank you, very good. Let us discuss tomorrow in detail this.

2015-11-19 17:19 GMT+01:00 Mian Muhammad Bilal Shabbir <
notifications@github.com>:
